### ISSUE TITLE
项目目录结构

### ISSUE THREAD

**Issue by naming1086** [sombie007/RPA#1]
Hi 大佬 我是昨天小专栏看完你在小专栏里面写的一些文章
你写了关于配置和测试目录 我都很感兴趣 期望你能写一个项目目录结构和相关的文章

例如(以下摘自你的文章):

Config.xlsx文件。(Settings/Contants/Assets三个Sheet页,在本项目中主要使用Setting页，其中包含了机器人存放的基础路径配置(Base_Work_Path)、用户配置文件的路径配置（User_Config_Path）。)

User Config.xlsx文件。包含了允许用户配置的一些参数。如各种系统桌面软件的可执行文件的路径(SAP、电子开票软件等)、各种系统登录时用到的凭证、在某些系统中需要查询数据用到的筛选条件以及用于接收反馈邮件的用户邮箱等。

通用模块.单独的Sequence或者Flowchart

测试文件.放在Test/Test_Framework文件夹中，测试文件命名使用Test后缀或者使用Test_进行修饰。

以上

**Comment by naming1086** [comment]
我已经找到了
https://github.com/mihhdu/Enhanced-REFramework

**Comment by sombie007** [comment]
> 我已经找到了
> https://github.com/mihhdu/Enhanced-REFramework
可以参考这个，但是我觉得REFramework依赖的东西还是比较多，不适合小流程的使用。

**Comment by sombie007** [comment]
> 我已经找到了
> https://github.com/mihhdu/Enhanced-REFramework
